micronaut:
  application:
    name: micronautguide
netty:
  default:
    allocator:
      max-order: 3
github:
  organization: micronaut-projects
  repo: micronaut-core
  username: yourgithubusername
  token: xxxxxxxxxxxx